



class Assay:
    def __init__(self, lelem):

        self.name = lelem[0]
        self.charac = {}


        if len(lelem) == 81:
            self.charac["assay_component_endpoint_name"] = lelem[0]
            self.charac["aeid"]  = lelem[1]
            self.charac["export_ready"]  = lelem[2]
            self.charac["internal_ready"]  = lelem[3]
            self.charac["assay_component_endpoint_desc"]  = lelem[4]
            self.charac["assay_function_type"]  = lelem[5]
            self.charac["normalized_data_type"]  = lelem[6]
            self.charac["analysis_direction"]  = lelem[7]
            self.charac["burst_assay"]  = lelem[8]
            self.charac["key_positive_control"]  = lelem[9]
            self.charac["signal_direction"]  = lelem[10]
            self.charac["intended_target_type"]  = lelem[11]
            self.charac["intended_target_type_sub"]  = lelem[12]
            self.charac["intended_target_family"]  = lelem[13]
            self.charac["intended_target_family_sub"]  = lelem[14]
            self.charac["fit_all"]  = lelem[15]
            self.charac["assay_source_name"]  = lelem[16]
            self.charac["assay_source_long_name"]  = lelem[17]
            self.charac["assay_source_desc"]  = lelem[18]
            self.charac["source_group"]  = lelem[19]
            self.charac["stress_process"]  = lelem[20]
            self.charac["acid"]  = lelem[21]
            self.charac["assay_component_name"]  = lelem[22]
            self.charac["assay_component_desc"]  = lelem[23]
            self.charac["assay_component_target_desc"]  = lelem[24]
            self.charac["parameter_readout_type"]  = lelem[25]
            self.charac["assay_design_type"]  = lelem[26]
            self.charac["assay_design_type_sub"]  = lelem[27]
            self.charac["biological_process_target"]  = lelem[28]
            self.charac["detection_technology_type"]  = lelem[29]
            self.charac["detection_technology_type_sub"]  = lelem[30]
            self.charac["detection_technology"]  = lelem[31]
            self.charac["signal_direction_type"]  = lelem[32]
            self.charac["key_assay_reagent_type"]  = lelem[33]
            self.charac["key_assay_reagent"]  = lelem[34]
            self.charac["technological_target_type"]  = lelem[35]
            self.charac["technological_target_type_sub"]  = lelem[36]
            self.charac["aid"]  = lelem[37]
            self.charac["assay_name"]  = lelem[38]
            self.charac["asid"]  = lelem[39]
            self.charac["assay_desc"]  = lelem[40]
            self.charac["timepoint_hr"]  = lelem[41]
            self.charac["organism_id"]  = lelem[42]
            self.charac["organism"]  = lelem[43]
            self.charac["tissue"]  = lelem[44]
            self.charac["cell_format"]  = lelem[45]
            self.charac["cell_free_component_source"]  = lelem[46]
            self.charac["cell_short_name"]  = lelem[47]
            self.charac["cell_growth_mode"]  = lelem[48]
            self.charac["assay_footprint"]  = lelem[49]
            self.charac["assay_format_type"]  = lelem[50]
            self.charac["assay_format_type_sub"]  = lelem[51]
            self.charac["content_readout_type"]  = lelem[52]
            self.charac["dilution_solvent"]  = lelem[53]
            self.charac["dilution_solvent_percent_max"]  = lelem[54]
            self.charac["intended_target_entrez_gene_id"]  = lelem[55]
            self.charac["intended_target_official_full_name"]  = lelem[56]
            self.charac["intended_target_gene_name"]  = lelem[57]
            self.charac["intended_target_official_symbol"]  = lelem[58]
            self.charac["intended_target_gene_symbol"]  = lelem[59]
            self.charac["intended_target_description"]  = lelem[60]
            self.charac["intended_target_uniprot_accession_number"]  = lelem[61]
            self.charac["intended_target_ncbi_taxon_id"]  = lelem[62]
            self.charac["intended_target_taxon_name"]  = lelem[63]
            self.charac["intended_target_common_name"]  = lelem[64]
            self.charac["technological_target_entrez_gene_id"]  = lelem[65]
            self.charac["technological_target_official_full_name"]  = lelem[66]
            self.charac["technological_target_gene_name"]  = lelem[67]
            self.charac["technological_target_official_symbol"]  = lelem[68]
            self.charac["technological_target_gene_symbol"]  = lelem[69]
            self.charac["technological_target_description"]  = lelem[70]
            self.charac["technological_target_uniprot_accession_number"]  = lelem[71]
            self.charac["technological_target_ncbi_taxon_id"]  = lelem[72]
            self.charac["technological_target_taxon_name"]  = lelem[73]
            self.charac["technological_target_common_name"]  = lelem[74]
            self.charac["pmid"] = lelem[75]
            self.charac["citation"] = lelem[76]
            self.charac["title"] = lelem[77]
            self.charac["author"] = lelem[78]
            self.charac["url"] = lelem[79]
            self.charac["update"] = lelem[80]

